version: '3'
services:
  subito-searcher:
    build: .
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - MONITOR_URLS=${MONITOR_URLS}
      - CHECK_INTERVAL=${CHECK_INTERVAL}